### ISSUE TITLE
Zend\Stratigility\MiddlewareInterface not found

### ISSUE THREAD

**Issue by lubos-h** [migratetoflarum/redirects#1]
Hello all, just tried out to install Redirects extension but whole forum crashes with error:

Interface 'Zend\Stratigility\MiddlewareInterface' not found in <my_project_path>\forum\vendor\migratetoflarum\redirects\src\Middlewares\RedirectMiddleware.php on line 18

Installed <my_project_path>\forum>composer require zendframework/zend-stratigility but still getting same error.

Any ideas please?

Thank you for the extension, seems very promising for my use case!

**Comment by clarkwinkelmann** [comment]
Hi. This extension stopped working a year ago when beta 8 was released. It was marked as incompatible on discuss.flarum.org, but due to the Composer requirements that were used at the time it can still be installed.

There is no plan to update it at this time, due to the very few downloads it got at the time and the fact none of my clients ended up using it.

I have just marked the package as abandoned on Packagist, that way future downloaders will get a warning if they install it.

If you still need the extension, you can contact me to get it updated through commissioned work https://clarkwinkelmann.com/flarum

I will close this issue as it's otherwise a "won't fix". I should probably archive the repo.

**Comment by lubos-h** [comment]
Thank you Clark, all the best!
